[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@yearnvaults/=lib/yearn-vaults/',
    '@openzeppelin/=lib/openzeppelin-contracts/'
]
fs_permissions = [{ access = "read", path = "./"}]

# See more config options https://github.com/gakonst/foundry/tree/master/config
